### ISSUE TITLE
First Steps

### ISSUE THREAD

**Issue by JnyJny** [menollycg/battleship#1]
Here's a short check list of things to do in the short term:

- [x] Create a README.md, can be empty
- [x] Create a subdirectory called `battleship` where the code lives.
- [x] Create an empty file `battleship/__init__.py`
- [x] Create an empty file `battleship/__main__.py`
- [x] Remove requests as a dependency `poetry remove requests`
- [x] Check in the changes

**Comment by lizmarie-dev** [comment]
Steps completed.
