### ISSUE TITLE
Bug - Pygame missing from requirements pyproject.toml

### ISSUE THREAD

**Issue by JnyJny** [menollycg/battleship#4]
First off, hell yeah! So proud of you!

It looks like you added pygame directly to your development environment using `pip install pygame` instead of using poetry `poetry add pygame`.

Using poetry makes sure that requirements get captured in the pyproject.toml file and ensures that your package is viable when installed in a new environment.

Simple fix :)

Edit: It occurred to me you might have just forgotten to commit changes to pyproject.toml and poetry.lock, either way the fixes are pretty easy. Let me know if you run into trouble figuring it out.

**Comment by lizmarie-dev** [comment]
Fixed.  I actually had used pip because I'm so used to it but used poetry and so the requirements got captured in the pyproject.toml file.

**Comment by JnyJny** [comment]
Point of order :) you don't get to close the issue until the fix is verified by the person who opened the issue :)

**Comment by JnyJny** [comment]
You've said it's fixed, but the issue isn't really "fixed" until the updated files have been committed and pushed up to GitHub.

**Comment by JnyJny** [comment]
And now we've temporarily removed PyGame as a dependency, so time to remove it :)

**Comment by JnyJny** [comment]
I'll open a separate issue to remove it.
