### ISSUE TITLE
Bug - FileNotFoundError on startup

### ISSUE THREAD

**Issue by JnyJny** [menollycg/battleship#5]
Once I got pygame installed in my environment (#4), the following happens when I run the game:

```console
<venv> $ python3 -m battleship
pygame 2.5.2 (SDL 2.28.3, Python 3.12.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/ejo/clients/PDM/LizW/battleship/battleship/__main__.py", line 9, in <module>
    BG = pygame.transform.scale(pygame.image.load("./images/background3.jpg"), (WIDTH, HEIGHT))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No file './images/background3.jpg' found in working directory '/Users/ejo/clients/PDM/LizW/battleship'.
```

This is a pretty common problem with an easy fix.  The problem is the path given `"./images/background3.jpg"` is a relative path (relative to the current directory). When I ran the program, my current directory was the top level directory of the project. The relative path to `background3.jpg` was really `./battleship/images/background3.jpg`.  When packaging data with our code, there are a couple of tricks we can use to avoid these broken relative paths. 

The first trick is using `pathlib.Path` and the `__file__` global variable:

```python
# battleship/__main__.py
...
from pathlib import Path
...
this_file = Path(__file__).resolve()
pg_path = this_file.parent / "images/background3.jpg"

BG = pygame.transform.scale(pygame.image.load(bg_path), (WIDTH, HEIGHT))
```

First, the `__file__` variable has the file system name for the current module. In this case, `__file__` is the string `"__main__.py"`.  Using `pathlib.Path`, we create a `Path` instance and call the `resolve` method which takes relative paths and attempts to "resolve" them into absolute paths.  This results in something like (on my machine):

```
>> p = Path(__file__).resolve()
>> print(p)
"/Users/ejo/clients/PDM/LizW/battleship/battleship/__main__.py"
>> print(p.parent)
"/Users/ejo/clients/PDM/LizW/battleship/battleship"
```
We know where the background JPG is stored relative to this file, so we can use the `parent` attribute of the `Path` to trim off the last part of the path, `"__main__.py"`, and then we append the relative path to the JPG to create a good absolute path.

This is a tried and true method for "finding" non Python files that are part of a package.

Another method is using `importlib.metadata`:

```
# battleship/__main__.py

...
from importlib.metadata import distribution

dist = distribution("battleship")
background = dist.locate_file("background3.jpg")
BG = pygame.transform.scale(pygame.image.load(background), (WIDTH, HEIGHT))
```

This is a more modern way of locating files in package, new in version 3.7 IIRC. As you can see, this method doesn't rely on anything more complicated than the name of the file you are looking for.  Once I added either of these two methods to your code, the pygame window popped up displaying the background JPEG.

**Comment by lizmarie-dev** [comment]
So I tried fixing this bug with the second way however it threw up errors on my end.  The first suggestion worked though.

**Comment by JnyJny** [comment]
Fixed it!
